import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Resource {
  id: string;
  name: string;
  type: string;
  total: number;
  occupied: number;
  available: number;
  threshold?: number;
  unit?: string;
}

interface NetworkResource extends Resource {
  hospital: string;
  city: string;
  hospital_id: string;
}

interface ExportResourcesOptions {
  hospitalName: string;
  resources: Resource[];
  userName: string;
}

interface ExportNetworkResourcesOptions {
  resources: NetworkResource[];
  userName: string;
}

export const exportResourcesToPDF = ({
  hospitalName,
  resources,
  userName,
}: ExportResourcesOptions): string => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Header with border
  doc.setFillColor(16, 185, 129); // Primary green color
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Logo/Icon placeholder
  doc.setFillColor(255, 255, 255);
  doc.circle(20, 17, 8, 'F');
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(16);
  doc.text('♥', 20, 20, { align: 'center' });
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Mint Health Hub', 35, 15);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Resource Availability Report', 35, 25);
  
  // Hospital Info Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(14, 45, pageWidth - 28, 30, 3, 3, 'FD');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Hospital:', 20, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(hospitalName, 45, 55);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', 20, 63);
  doc.setFont('helvetica', 'normal');
  doc.text(userName, 50, 63);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 20, 71);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleString(), 35, 71);
  
  // Group resources by type
  const resourcesByType: Record<string, Resource[]> = {
    bed: [],
    oxygen: [],
    blood: [],
    ventilator: [],
  };
  
  resources.forEach(r => {
    if (resourcesByType[r.type]) {
      resourcesByType[r.type].push(r);
    }
  });
  
  let yPosition = 85;
  
  // Resource type labels
  const typeLabels: Record<string, string> = {
    bed: '🛏️ Beds',
    oxygen: '💨 Oxygen',
    blood: '🩸 Blood Bank',
    ventilator: '🫁 Ventilators',
  };
  
  Object.entries(resourcesByType).forEach(([type, items]) => {
    if (items.length === 0) return;
    
    // Section header
    doc.setFillColor(243, 244, 246);
    doc.rect(14, yPosition, pageWidth - 28, 8, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(typeLabels[type] || type.toUpperCase(), 20, yPosition + 5.5);
    
    yPosition += 12;
    
    // Table for this resource type
    autoTable(doc, {
      startY: yPosition,
      head: [['Resource Name', 'Total', 'In Use', 'Available', 'Usage %', 'Status']],
      body: items.map(r => {
        const usagePercent = Math.round((r.occupied / r.total) * 100);
        const status = r.available < (r.threshold || 5) ? '⚠️ Low' : 
                      r.available < (r.threshold || 5) * 2 ? '⚡ Medium' : '✅ Good';
        
        return [
          r.name,
          r.total.toString(),
          r.occupied.toString(),
          r.available.toString(),
          `${usagePercent}%`,
          status,
        ];
      }),
      theme: 'striped',
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 10,
      },
      bodyStyles: {
        fontSize: 9,
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        // Footer on each page
        const footerY = pageHeight - 15;
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${data.pageNumber} | Generated on ${new Date().toLocaleDateString()}`,
          pageWidth / 2,
          footerY,
          { align: 'center' }
        );
      },
    });
    
    yPosition = ((doc as unknown) as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
    
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }
  });
  
  // Summary section
  const totalResources = resources.reduce((sum, r) => sum + r.total, 0);
  const totalOccupied = resources.reduce((sum, r) => sum + r.occupied, 0);
  const totalAvailable = resources.reduce((sum, r) => sum + r.available, 0);
  const overallUsage = Math.round((totalOccupied / totalResources) * 100);
  
  if (yPosition > pageHeight - 60) {
    doc.addPage();
    yPosition = 20;
  }
  
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(14, yPosition, pageWidth - 28, 35, 3, 3, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Summary', 20, yPosition + 10);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Capacity: ${totalResources}`, 20, yPosition + 18);
  doc.text(`Currently In Use: ${totalOccupied}`, 20, yPosition + 25);
  doc.text(`Available: ${totalAvailable}`, pageWidth / 2, yPosition + 18);
  doc.text(`Overall Usage: ${overallUsage}%`, pageWidth / 2, yPosition + 25);
  
  // Save the PDF
  const filename = `${hospitalName.replace(/\s+/g, '_')}_Resources_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
  
  return filename;
};

export const exportNetworkResourcesToPDF = ({
  resources,
  userName,
}: ExportNetworkResourcesOptions): string => {
  const doc = new jsPDF('landscape'); // Landscape for wider table
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Header
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setFillColor(255, 255, 255);
  doc.circle(20, 17, 8, 'F');
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(16);
  doc.text('♥', 20, 20, { align: 'center' });
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Mint Health Hub', 35, 15);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Network Resources Report', 35, 25);
  
  // Info Box
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(249, 250, 251);
  doc.roundedRect(14, 45, pageWidth - 28, 20, 3, 3, 'FD');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', 20, 55);
  doc.setFont('helvetica', 'normal');
  doc.text(userName, 50, 55);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Date:', 20, 62);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date().toLocaleString(), 35, 62);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Total Hospitals:', pageWidth / 2, 55);
  doc.setFont('helvetica', 'normal');
  const hospitalCount = new Set(resources.map(r => r.hospital_id)).size;
  doc.text(hospitalCount.toString(), pageWidth / 2 + 35, 55);
  
  // Group by type
  const resourcesByType: Record<string, NetworkResource[]> = {
    bed: [],
    oxygen: [],
    blood: [],
    ventilator: [],
  };
  
  resources.forEach(r => {
    if (resourcesByType[r.type]) {
      resourcesByType[r.type].push(r);
    }
  });
  
  let yPosition = 75;
  
  const typeLabels: Record<string, string> = {
    bed: '🛏️ Beds',
    oxygen: '💨 Oxygen',
    blood: '🩸 Blood Bank',
    ventilator: '🫁 Ventilators',
  };
  
  Object.entries(resourcesByType).forEach(([type, items]) => {
    if (items.length === 0) return;
    
    // Section header
    doc.setFillColor(243, 244, 246);
    doc.rect(14, yPosition, pageWidth - 28, 8, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(typeLabels[type] || type.toUpperCase(), 20, yPosition + 5.5);
    
    yPosition += 12;
    
    // Table
    autoTable(doc, {
      startY: yPosition,
      head: [['Hospital', 'City', 'Resource', 'Total', 'In Use', 'Available', 'Usage %']],
      body: items.map(r => {
        const usagePercent = Math.round((r.occupied / r.total) * 100);
        return [
          r.hospital,
          r.city,
          r.name,
          r.total.toString(),
          r.occupied.toString(),
          r.available.toString(),
          `${usagePercent}%`,
        ];
      }),
      theme: 'striped',
      headStyles: {
        fillColor: [16, 185, 129],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        const footerY = pageHeight - 10;
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${data.pageNumber} | Network Resources Report | ${new Date().toLocaleDateString()}`,
          pageWidth / 2,
          footerY,
          { align: 'center' }
        );
      },
    });
    
    yPosition = ((doc as unknown) as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
    
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = 20;
    }
  });
  
  const filename = `Network_Resources_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
  
  return filename;
};
